### ISSUE TITLE
Operating system could not be determined

### ISSUE THREAD

**Issue by richrumble** [giMini/RWMC#4]
# (64-bit Windows 10 Enterprise)

Do you want use Active Directory cmdlets ?
1) Yes
2) No
0) Exit
Enter menu number and press <ENTER>: 2
Local computer, Remote computer or from a dump file ?
1) Local
2) Remote
3) lsass process .dmp
4) VM snapshot .dmp
0) Exit
# Enter menu number and press <ENTER>: 1

The operating system could not be determined... terminating...
Script terminating...

PS C:\Intel\Reveal-MemoryCredentials> [environment]::OSVersion.Version
Major  Minor  Build  Revision

---

10     0      10586  0
PS C:\Intel\Reveal-MemoryCredentials> (Get-WmiObject Win32_OperatingSystem).OSArchitecture
64-bit

I'll try to get a memory dump if you need it.

**Comment by giMini** [comment]
Hi,

RWMC tool alone is not more supported.

It has been included to my PowerMemory suite : https://github.com/giMini/PowerMemory

Can you try it and tell me if you have an issue ?

Thanks,
